name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: tiralabra
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: tiralabra
    - name: Test with Gradle
      run: ./gradlew test
      working-directory: tiralabra
    - name: Code coverage report
      run: ./gradlew jacocoTestReport
      working-directory: tiralabra
    - name: Data to codecov
      run: bash <(curl -s https://codecov.io/bash)
      working-directory: tiralabra
    - name: Data to codecov
      run: ./gradlew checkstyleMain
      working-directory: tiralabra